import React, { useState } from 'react';
import { Text, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useAppDispatch } from '../../../features/stateHooks';
import { ThemeContextType, useTheme } from '../../../theme/ThemeContext';
import { setSession } from '../../slices/authSlice';
import AuthInput from '../../components/AuthInput';
import AuthButton from '../../components/AuthButton';
import { buildLoginPayload, login, signUp } from '../../services/authApi';
import { saveAuthSession } from '../../services/authStorage';
import { AuthStackParamList } from '../../navigation/types';
import { generatePasswordForUser } from '../../utils/password';
import { createStyles } from './styles';

type Props = NativeStackScreenProps<AuthStackParamList, 'Signup'>;

const SignUpScreen = ({ route }: Props) => {
    const dispatch = useAppDispatch();
    const { colors }: ThemeContextType = useTheme();
    const styles = createStyles(colors);
    const { username } = route.params;
    const [fullName, setFullName] = useState('');
    const [loading, setLoading] = useState(false);
    const [errorMessage, setErrorMessage] = useState('');

    const handleSignup = async () => {
        const normalizedName = fullName.trim();
        setErrorMessage('');

        if (normalizedName.length < 2) {
            setErrorMessage('Enter your full name.');
            return;
        }

        setLoading(true);
        try {
            const autoGeneratedPassword = generatePasswordForUser(username);

            await signUp({
                username,
                password: autoGeneratedPassword,
                fullName: normalizedName,
            });

            const loginPayload = buildLoginPayload(username, autoGeneratedPassword);
            const session = await login(loginPayload);
            await saveAuthSession(session);
            dispatch(setSession(session));
        } catch (error: any) {
            setErrorMessage(error?.message ?? 'Signup failed.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <View style={styles.container}>
            <Text style={styles.heading}>Profile Creation</Text>
            <Text style={styles.subtitle}>
                Your account is verified. Complete your profile to continue.
            </Text>

            <AuthInput
                label="Email / Mobile"
                value={username}
                onChangeText={() => {}}
                placeholder=""
                editable={false}
            />

            <AuthInput
                label="Full Name"
                value={fullName}
                onChangeText={setFullName}
                placeholder="Enter full name"
                autoCapitalize="words"
            />

            {errorMessage ? <Text style={styles.inlineError}>{errorMessage}</Text> : null}

            <AuthButton
                title="Continue"
                onPress={handleSignup}
                disabled={fullName.trim().length === 0}
                loading={loading}
            />
        </View>
    );
};

export default SignUpScreen;
