import React, { useState } from 'react';
import { Text, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useAppDispatch } from '../../../features/stateHooks';
import { ThemeContextType, useTheme } from '../../../theme/ThemeContext';
import { setSession } from '../../slices/authSlice';
import AuthInput from '../../components/AuthInput';
import AuthButton from '../../components/AuthButton';
import {
    buildLoginPayload,
    login,
    signUp,
    updateOptionalExamBoard,
    updateOptionalUserType,
} from '../../services/authApi';
import { saveAuthSession } from '../../services/authStorage';
import { AuthStackParamList } from '../../navigation/types';
import { generatePasswordForUser } from '../../utils/password';
import { createStyles } from './styles';

type Props = NativeStackScreenProps<AuthStackParamList, 'Signup'>;

const SignUpScreen = ({ route }: Props) => {
    const dispatch = useAppDispatch();
    const { colors }: ThemeContextType = useTheme();
    const styles = createStyles(colors);
    const { username } = route.params;
    const [fullName, setFullName] = useState('');
    const [examBoard, setExamBoard] = useState('GCE_ENGLISH');
    const [loading, setLoading] = useState(false);
    const [errorMessage, setErrorMessage] = useState('');

    const handleSignup = async () => {
        const normalizedName = fullName.trim();
        const normalizedExamBoard = examBoard.trim().toUpperCase().replace(/\s+/g, '_');
        setErrorMessage('');

        if (normalizedName.length < 2) {
            setErrorMessage('Enter your full name.');
            return;
        }

        if (normalizedExamBoard.length < 2) {
            setErrorMessage('Enter your exam board.');
            return;
        }

        setLoading(true);
        try {
            const autoGeneratedPassword = generatePasswordForUser(username);
            const signupPayload = {
                username,
                password: autoGeneratedPassword,
                fullName: normalizedName,
            };

            try {
                await signUp(signupPayload);
                console.log('[AUTH][PROFILE] signup completed', {
                    username,
                });
            } catch (signupError: any) {
                const statusCode = signupError?.statusCode ?? null;
                const isAlreadyExists = statusCode === 409 || statusCode === 403;

                console.log('[AUTH][PROFILE] signup failed', {
                    username,
                    statusCode,
                    message: signupError?.message ?? null,
                    responseData: signupError?.responseData ?? null,
                    fallbackToLogin: isAlreadyExists,
                });

                if (!isAlreadyExists) {
                    throw signupError;
                }
            }

            const loginPayload = buildLoginPayload(username, autoGeneratedPassword);
            const session = await login(loginPayload);
            await updateOptionalUserType(session.token, 'STUDENT');
            await updateOptionalExamBoard(session.token, normalizedExamBoard);
            await saveAuthSession(session);
            dispatch(setSession(session));
        } catch (error: any) {
            setErrorMessage(error?.message ?? 'Signup failed.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <View style={styles.container}>
            <Text style={styles.heading}>Profile Creation</Text>
            <Text style={styles.subtitle}>
                Your account is verified. Complete your profile to continue.
            </Text>

            <AuthInput
                label="Full Name"
                value={fullName}
                onChangeText={setFullName}
                placeholder="Enter full name"
                autoCapitalize="words"
            />

            <AuthInput
                label="Exam Board"
                value={examBoard}
                onChangeText={setExamBoard}
                placeholder="e.g. GCE_ENGLISH"
                autoCapitalize="characters"
            />

            {errorMessage ? <Text style={styles.inlineError}>{errorMessage}</Text> : null}

            <AuthButton
                title="Continue"
                onPress={handleSignup}
                disabled={fullName.trim().length === 0 || examBoard.trim().length === 0}
                loading={loading}
            />
        </View>
    );
};

export default SignUpScreen;
